#ifndef  ERRORS_H
#define  ERRORS_H

#define RETURN_NO_ERROR return ERROR_NOERROR

#define ERROR_NOERROR 0

#define ERROR_SERIALPORT_OPEN 100
#define ERROR_SERIALPORT_NOT_SUPPORTED 101

#endif /* ERRORS_H */
